// RideTheRailsTrackPoints.web/src/components/game/PlayerComponent.vue
<script>
import Color from "./Color.vue";
export default {
    name: "playerComponent",
    props: {
        editable: {
            type: Boolean,
            required: false,
            default: false,
        },
        player: {
            required: true,
            default: {
                name: "",
                colors: ""
            }
        },
    },
    data() {
        return {}
    },
    methods: {
        colorClicked() {
            this.player.check = !this.player.check
        },
        changeName(event) {
            this.player.name = event.target.value
        }
    },
    computed: {
    },
    components: { Color }
}
</script>

<template>
    <div class="player">
        <Color :color="player.color" :check="player.check" @color-clicked="colorClicked"></Color>
        <div v-if="editable">
            <input v-show="player.check" type="text" v-model="player.name" placeholder="Insert a name" required />
        </div>
        <div v-else>
            <label>{{ player.name }} - {{ player.points }}</label>
        </div>
    </div>
</template>

<style>
.player {
    display: flex;
    flex-direction: row;
    justify-content: start;
}
</style>

// ridetherailstrackpoints.react/components/Game/PlayerComponent.tsx
import PlayerInterface from "@/interfaces/PlayerInterface"
import { useState } from "react"
import ColorComponent from "./ColorComponent"

type PlayerComponentProps = {
    player: PlayerInterface
    checked: boolean
    onNameChange?: any
    onColorClick?: any
}

export default function PlayerComponent ({player, checked, onColorClick, onNameChange} : PlayerComponentProps)  {

    return <>
    <div className="flex p-4 flex-row content-center items-center">
        <ColorComponent color={player.color} check={checked} onClick={onColorClick}/>
        {
            checked && (
                <>
                <div className="pl-4">
                {
                    onNameChange
                    ? checked && (<input type="text" defaultValue={player.name} onChange={onNameChange}></input>)
                    : (<label>{player.name}</label>)
                }
                </div>
                </>
            )
        }
        
    </div>
    </>
}
